# Generated by Django 5.1.7 on 2026-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='sku',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
